# Generated by Django 4.2.13 on 2024-11-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest_name',
            new_name='name',
        ),
    ]
