# Generated by Django 4.2.13 on 2024-11-19 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('actual_position', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('profile_picture', models.URLField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cellphone', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('github', models.TextField(default='')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
